import{S as y,a as h,i as c}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const p=new y(".gallery a",{captionsData:"alt",captionDelay:300});function g(t,r){const o=document.querySelector(".js-gallery-list");if(r&&(o.innerHTML=""),t.length===0&&r){iziToast.error({message:"Sorry, there are no images matching your search. Please try again!"});return}const l=t.map(e=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${e.largeImageURL}">
                        <img src="${e.webformatURL}" alt="${e.tags}">
                    </a>
                    <ul class="item-info">
                        <li class="item-list"><h3>Likes</h3><p>${e.likes}</p></li>
                        <li class="item-list"><h3>Views</h3><p>${e.views}</p></li>
                        <li class="item-list"><h3>Comments</h3><p>${e.comments}</p></li>
                        <li class="item-list"><h3>Downloads</h3><p>${e.downloads}</p></li>
                    </ul>
                </li>
            `).join("");o.insertAdjacentHTML("beforeend",l),p.refresh()}const L="https://pixabay.com/api/",b="44095628-d0027d9df3d6429662d87f006",S=(t,r)=>h.get(L,{params:{q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15,key:b}}),u=document.querySelector(".search-form"),w=document.querySelector(".search-input"),m=document.getElementById("loader"),v=document.querySelector(".js-gallery-list"),i=document.querySelector(".js-load-more");i.classList.add("is-hiden");let a=1,d="";const E=()=>{a+=1,f(a,!1)};i.addEventListener("click",E);u.addEventListener("submit",async t=>{if(t.preventDefault(),d=w.value.trim(),d===""){c.error({title:"Error:",message:"Please enter a search term.",position:"topRight"});return}v.innerHTML="",a=1,f(a,!0),u.reset()});const f=async(t,r)=>{try{m.style.display="block",i.classList.add("is-hiden");const o=await S(d,t),l=o.data.hits;if(g(l,r),t>1&&q(),o.data.totalHits<=t*15){c.info({message:"We're sorry, but you've reached the end of search results."});return}i.classList.remove("is-hiden")}catch{c.error({title:"Error:",message:"An error occurred while fetching images. Please try again later."})}finally{m.style.display="none"}},q=()=>{const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height*2;window.scrollBy({top:o,left:0,behavior:"smooth"})}};
//# sourceMappingURL=commonHelpers.js.map
