import{S as f,a as h,i as c}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();const p=new f(".gallery a",{captionsData:"alt",captionDelay:300});function g(t){const r=document.querySelector(".js-gallery-list");if(r.innerHTML="",t.length===0){iziToast.error({message:"Sorry, there are no images matching your search. Please try again!"});return}const l=t.map(o=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${o.largeImageURL}">
                        <img src="${o.webformatURL}" alt="${o.tags}">
                    </a>
                    <ul class="item-info">
                        <li class="item-list"><h3>Likes</h3><p>${o.likes}</p></li>
                        <li class="item-list"><h3>Views</h3><p>${o.views}</p></li>
                        <li class="item-list"><h3>Comments</h3><p>${o.comments}</p></li>
                        <li class="item-list"><h3>Downloads</h3><p>${o.downloads}</p></li>
                    </ul>
                </li>
            `).join("");r.innerHTML=l,p.refresh()}const L="https://pixabay.com/api/",w="44095628-d0027d9df3d6429662d87f006",S=(t,r)=>h.get(L,{params:{q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15,key:w}}),u=document.querySelector(".search-form"),b=document.querySelector(".search-input"),m=document.getElementById("loader"),v=document.querySelector(".js-gallery-list"),i=document.querySelector(".js-load-more");i.classList.add("is-hiden");let a=1,d="";const E=()=>{a+=1,y(a)};i.addEventListener("click",E);u.addEventListener("submit",async t=>{if(t.preventDefault(),d=b.value.trim(),d===""){c.error({title:"Error:",message:"Please enter a search term.",position:"topRight"});return}v.innerHTML="",a=1,y(a),u.reset()});const y=async t=>{try{m.style.display="block",i.classList.add("is-hiden");const r=await S(d,t),l=r.data.hits;if(await g(l),t>1&&q(),r.data.totalHits<=t*15){c.info({message:"We're sorry, but you've reached the end of search results."});return}i.classList.remove("is-hiden")}catch{c.error({title:"Error:",message:"An error occurred while fetching images. Please try again later."})}finally{m.style.display="none"}},q=()=>{const t=document.querySelector(".gallery-item");if(t){const l=t.getBoundingClientRect().height*2;window.scrollBy({top:l,left:0,behavior:"smooth"})}};
//# sourceMappingURL=commonHelpers.js.map
